/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestPanel.java
 *
 * Created on 2013-feb-20, 11:26:54
 */
package imat;

import java.awt.event.ActionEvent;

import java.util.List;
import javax.swing.ImageIcon;

import se.chalmers.ait.dat215.project.*;
/**
 *
 * @author victorsandell
 */
public class FoodPanel extends javax.swing.JPanel {
    
    private void addItemsToCart(int amount) {
        List<ShoppingItem> sList = IMatDataHandler.getInstance().getShoppingCart().getItems();
        
        double tmp = 0;
        for(ShoppingItem s : sList){
            if(s.getProduct() == p){
                tmp = s.getAmount();
                IMatDataHandler.getInstance().getShoppingCart().removeItem(s);
                IMatDataHandler.getInstance().getShoppingCart().addProduct(p, tmp+amount);
                return;
            }
        }
        IMatDataHandler.getInstance().getShoppingCart().addProduct(p, amount);
    }
    /** Creates new form TestPanel */
    public FoodPanel(Product p, int width, int height) {
        initComponents();
        plusButton.setIcon(new ImageIcon(getClass().getResource("resources/plusButton.png")));
        plusButton.setRolloverIcon(new ImageIcon(getClass().getResource("resources/plusButtonHover.png")));
        plusButton.setPressedIcon(new ImageIcon(getClass().getResource("resources/plusButtonClicked.png")));
        plusButton.setBorderPainted(false);
        
        this.p = p;
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent e) {
                ShoppingCart cart = IMatDataHandler.getInstance().getShoppingCart();
                int amount;
                try {
                    amount = Integer.parseInt(amountField.getText());
                } catch (NumberFormatException ex) {
                    amount = 0;
                }
                if(amount != 0){
                    addItemsToCart(amount);
                }
            }
        });
        this.width = width;
        this.height = height;
        
        imageLabel.setIcon(IMatDataHandler.getInstance().
            getImageIcon(p, width, height));
        nameLabel.setText(p.getName());
        priceUnitLabel.setText(p.getPrice() + " "+ p.getUnit());
        amountField.setText("1");
        
        setStar();
    }
        /*
    jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
         }
     * 
     */

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        priceUnitLabel = new javax.swing.JLabel();
        plusButton = new javax.swing.JButton();
        amountPanel = new javax.swing.JPanel();
        amountField = new javax.swing.JTextField();
        topLabel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        starButton = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(FoodPanel.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("Form.border.lineColor"))); // NOI18N
        setBounds(new java.awt.Rectangle(0, 0, 150, 175));
        setMaximumSize(new java.awt.Dimension(150, 175));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(125, 150));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        imageLabel.setBackground(resourceMap.getColor("imageLabel.background")); // NOI18N
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setText(resourceMap.getString("imageLabel.text")); // NOI18N
        imageLabel.setBounds(new java.awt.Rectangle(0, 0, 125, 120));
        imageLabel.setMaximumSize(new java.awt.Dimension(125, 120));
        imageLabel.setMinimumSize(new java.awt.Dimension(125, 120));
        imageLabel.setName("imageLabel"); // NOI18N
        imageLabel.setOpaque(true);
        imageLabel.setPreferredSize(new java.awt.Dimension(125, 120));
        add(imageLabel, java.awt.BorderLayout.CENTER);

        bottomPanel.setBackground(resourceMap.getColor("bottomPanel.background")); // NOI18N
        bottomPanel.setMaximumSize(new java.awt.Dimension(125, 25));
        bottomPanel.setMinimumSize(new java.awt.Dimension(125, 25));
        bottomPanel.setName("bottomPanel"); // NOI18N
        bottomPanel.setPreferredSize(new java.awt.Dimension(125, 25));
        bottomPanel.setLayout(new java.awt.BorderLayout());

        priceUnitLabel.setBackground(resourceMap.getColor("priceUnitLabel.background")); // NOI18N
        priceUnitLabel.setFont(resourceMap.getFont("priceUnitLabel.font")); // NOI18N
        priceUnitLabel.setForeground(resourceMap.getColor("priceUnitLabel.foreground")); // NOI18N
        priceUnitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceUnitLabel.setText(resourceMap.getString("priceUnitLabel.text")); // NOI18N
        priceUnitLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        priceUnitLabel.setName("priceUnitLabel"); // NOI18N
        priceUnitLabel.setPreferredSize(new java.awt.Dimension(80, 16));
        bottomPanel.add(priceUnitLabel, java.awt.BorderLayout.WEST);

        plusButton.setIcon(resourceMap.getIcon("plusButton.icon")); // NOI18N
        plusButton.setText(resourceMap.getString("plusButton.text")); // NOI18N
        plusButton.setBorderPainted(false);
        plusButton.setName("plusButton"); // NOI18N
        plusButton.setPreferredSize(new java.awt.Dimension(40, 24));
        bottomPanel.add(plusButton, java.awt.BorderLayout.EAST);

        amountPanel.setBackground(resourceMap.getColor("amountPanel.background")); // NOI18N
        amountPanel.setName("amountPanel"); // NOI18N
        amountPanel.setPreferredSize(new java.awt.Dimension(35, 25));

        amountField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        amountField.setMaximumSize(new java.awt.Dimension(5, 5));
        amountField.setMinimumSize(new java.awt.Dimension(25, 23));
        amountField.setName("amountField"); // NOI18N
        amountField.setOpaque(true);
        amountField.setPreferredSize(new java.awt.Dimension(25, 23));
        amountField.setVerifyInputWhenFocusTarget(false);
        amountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountFieldKeyTyped(evt);
            }
        });

        org.jdesktop.layout.GroupLayout amountPanelLayout = new org.jdesktop.layout.GroupLayout(amountPanel);
        amountPanel.setLayout(amountPanelLayout);
        amountPanelLayout.setHorizontalGroup(
            amountPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, amountPanelLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .add(amountField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        amountPanelLayout.setVerticalGroup(
            amountPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, amountField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        bottomPanel.add(amountPanel, java.awt.BorderLayout.CENTER);

        add(bottomPanel, java.awt.BorderLayout.SOUTH);

        topLabel.setBackground(resourceMap.getColor("topLabel.background")); // NOI18N
        topLabel.setMaximumSize(new java.awt.Dimension(125, 25));
        topLabel.setMinimumSize(new java.awt.Dimension(125, 25));
        topLabel.setName("topLabel"); // NOI18N
        topLabel.setPreferredSize(new java.awt.Dimension(125, 25));
        topLabel.setLayout(new java.awt.BorderLayout());

        nameLabel.setBackground(resourceMap.getColor("nameLabel.background")); // NOI18N
        nameLabel.setFont(resourceMap.getFont("nameLabel.font")); // NOI18N
        nameLabel.setForeground(resourceMap.getColor("nameLabel.foreground")); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
        nameLabel.setMaximumSize(new java.awt.Dimension(126, 16));
        nameLabel.setMinimumSize(new java.awt.Dimension(0, 0));
        nameLabel.setName("nameLabel"); // NOI18N
        nameLabel.setOpaque(true);
        nameLabel.setPreferredSize(new java.awt.Dimension(124, 16));
        topLabel.add(nameLabel, java.awt.BorderLayout.WEST);

        starButton.setBackground(resourceMap.getColor("starButton.background")); // NOI18N
        starButton.setIcon(resourceMap.getIcon("starButton.icon")); // NOI18N
        starButton.setText(resourceMap.getString("starButton.text")); // NOI18N
        starButton.setBorderPainted(false);
        starButton.setContentAreaFilled(false);
        starButton.setDefaultCapable(false);
        starButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        starButton.setMaximumSize(new java.awt.Dimension(24, 24));
        starButton.setMinimumSize(new java.awt.Dimension(24, 24));
        starButton.setName("starButton"); // NOI18N
        starButton.setPreferredSize(new java.awt.Dimension(24, 24));
        starButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starButtonActionPerformed(evt);
            }
        });
        topLabel.add(starButton, java.awt.BorderLayout.EAST);

        add(topLabel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

private void starButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starButtonActionPerformed
    if(evt.getSource() == starButton) {
        setFavorite();
    }
}//GEN-LAST:event_starButtonActionPerformed

private void amountFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountFieldKeyTyped
    char c = evt.getKeyChar();
    if(c < '0' || c > '9' || (amountField.getText().length() == 2)){
        evt.consume();
    }
}//GEN-LAST:event_amountFieldKeyTyped

public void setFavorite(){
    if(starButton.getIcon() == unselectedStar){
        starButton.setIcon(selectedStar);
        IMatDataHandler.getInstance().addFavorite(p);
    }else{
        starButton.setIcon(unselectedStar);
        IMatDataHandler.getInstance().removeFavorite(p);
    }
    IMatDataHandler.getInstance().shutDown();
}

public void setStar(){
    List<Product> favList = IMatDataHandler.getInstance().favorites();
        
        if(favList.contains(p)){
            starButton.setIcon(selectedStar);
        }else{
            starButton.setIcon(unselectedStar);
        }
}

public void setProperties(String name, int price, String unit){
    nameLabel.setText(name);
    priceUnitLabel.setText(price + " " + unit);
}

public void setIconSize(int width, int height){
    imageLabel.setIcon(IMatDataHandler.getInstance().
            getImageIcon(p, width, height));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JPanel amountPanel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton plusButton;
    private javax.swing.JLabel priceUnitLabel;
    private javax.swing.JButton starButton;
    private javax.swing.JPanel topLabel;
    // End of variables declaration//GEN-END:variables

    
    private ImageIcon selectedStar = new ImageIcon(getClass().getResource
            ("resources/starselected.png"));
    private ImageIcon unselectedStar = new ImageIcon(getClass().getResource
            ("resources/starunselected.png"));
    private Product p;
    private int height;
    private int width;
}
