/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * kvittoItemPanel.java
 *
 * Created on 2013-mar-06, 13:06:47
 */
package imat;
import se.chalmers.ait.dat215.project.*;
import javax.swing.*;

/**
 *
 * @author kimegenvall
 */
public class kvittoItemPanel extends javax.swing.JPanel {
    private ShoppingItem p;
    /** Creates new form kvittoItemPanel */
    public kvittoItemPanel(ShoppingItem p) {
        this.p = p;
        initComponents();
        updateKvittoFields();
    }
    
    public void updateKvittoFields(){
        
        jLabel1.setText(p.getProduct().getName());
        jLabel2.setText(p.getProduct().getPrice() + " " + p.getProduct().getUnit());
        jLabel3.setText(p.getAmount()+"");
        
        jLabel4.setText(Integer.toString((int)p.getTotal()) + " kr");
        revalidate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setName("Form"); // NOI18N

        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setName("jLabel4"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 94, Short.MAX_VALUE)
                .add(jLabel2)
                .add(65, 65, 65)
                .add(jLabel3)
                .add(81, 81, 81)
                .add(jLabel4)
                .add(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jLabel3)
                    .add(jLabel2)
                    .add(jLabel1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
