/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HistoryListPanel.java
 *
 * Created on 2013-mar-03, 17:55:58
 */
package imat;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import se.chalmers.ait.dat215.project.IMatDataHandler;
import se.chalmers.ait.dat215.project.Order;
import se.chalmers.ait.dat215.project.Product;
import se.chalmers.ait.dat215.project.ShoppingItem;

/**
 *
 * @author victorsandell
 */
public class SavedListItemPanel extends javax.swing.JPanel {

    public static int nameCount = 0;
    private SavedListsPanel jp;
    private ShoppingItemList shoppingItemList;
    private Order o;
    
    /** Creates new form HistoryListPanel */
    public SavedListItemPanel(SavedListsPanel jp, ShoppingItemList sil) {
        initComponents();
        
        this.jp = jp;
        nameCount++;
        shoppingItemList = sil;
        jLabel2.setText(sil.getName());
        jLabel4.setText(Integer.toString(sil.getAmount()));
        jLabel5.setText(Integer.toString(sil.getTotal()) + " kr");
    }
    
    public SavedListItemPanel(SavedListsPanel jp, Order o) {
       initComponents();
       
       this.o = o;
       this.jp = jp;
       
       nameCount++;
       shoppingItemList = new ShoppingItemList();
       for(ShoppingItem s : o.getItems()){
           shoppingItemList.add(s);
       }
       jLabel2.setText(o.getDate().toString().substring(0, 10));
       jLabel4.setText(Integer.toString(shoppingItemList.getAmount()));
       jLabel5.setText(Integer.toString(shoppingItemList.getTotal()) + " kr");
       jButton1.setEnabled(false);
       jButton1.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setName("Form"); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(SavedListItemPanel.class);
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(45, 45, 45)
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 126, Short.MAX_VALUE)
                .add(jButton3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .add(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .add(jButton3)
                .add(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    (IMatView.savedShoppingListItems).remove(shoppingItemList);
    jp.updateShoppingList();
    IMatView.splashPanel.addLatestPurchases();
    IMatView.splashPanel.addSavedPurchases(IMatView.savedShoppingListItems);
    ListSaveLoad.getInstance().saveList(IMatView.savedShoppingListItems);
    IMatDataHandler.getInstance().shutDown();
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    List<ShoppingItem> siList = IMatDataHandler.getInstance().getShoppingCart().getItems();
    List<ShoppingItem> sListTmp  = new ArrayList<ShoppingItem>(shoppingItemList.getProductList());
    List<ShoppingItem> sListTmp2  = new ArrayList<ShoppingItem>(shoppingItemList.getProductList());
    
    double tmp = 0;
    double amount = 0;
    for(ShoppingItem si : sListTmp){
        tmp = si.getAmount();
        for(ShoppingItem s : siList){
            amount = s.getAmount();
            if(s.getProduct() == si.getProduct()){
                IMatDataHandler.getInstance().getShoppingCart().removeItem(s);
                IMatDataHandler.getInstance().getShoppingCart().addProduct(s.getProduct(), tmp+amount);
                sListTmp2.remove(si);
                break;
            }
        }        
    }
    
    for(ShoppingItem s : sListTmp2){
        amount = s.getAmount();
        IMatDataHandler.getInstance().getShoppingCart().addProduct(s.getProduct(), amount);
    }
}//GEN-LAST:event_jButton3ActionPerformed

private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
    jp.addBottomItems(shoppingItemList);
}//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
