/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShoppingListPanel.java
 *
 * Created on 2013-feb-23, 00:27:30
 */
package imat;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;

import se.chalmers.ait.dat215.project.*;
/**
 *
 * @author victorsandell
 */
public class ShoppingListPanel extends javax.swing.JPanel {

    private List<ShoppingItem> sList;
    
    /** Creates new form ShoppingListPanel */
    public ShoppingListPanel(ShoppingItemList sil) {
        initComponents();
        
        jLabel1.setText(sil.getName());
        sList = sil.getProductList();
        List<ShoppingItem> tmp = sil.getProductList();
        jPanel2.setLayout(new GridLayout(3, 3));
        
        for(int i = 0; i < sil.size(); i++){
            ImageIcon icon = IMatDataHandler.getInstance().
                    getImageIcon(tmp.get(i).getProduct(), 60, 53);
            jPanel2.add(new FoodImagePanel(icon));
        }
        
        for(int n = 0; n < 9-sil.size(); n++){
            jPanel2.add(new FoodImagePanel(null));
        }
        
        //this.setPreferredSize(new Dimension(175, 500));
    }
    
    public ShoppingListPanel(Order o) {
        initComponents();
        sList = o.getItems();
        jLabel1.setText(o.getDate().toString());
        jPanel2.setLayout(new GridLayout(3,3));
        List<ShoppingItem> siList = o.getItems();
        
        for(ShoppingItem s : siList){
            ImageIcon icon = IMatDataHandler.getInstance().
                    getImageIcon(s.getProduct(), 60, 53);
            jPanel2.add(new FoodImagePanel(icon));
        }
        for(int n = 0; n < 9-sList.size(); n++){
            jPanel2.add(new FoodImagePanel(null));
        }        
        this.setPreferredSize(new Dimension(185, 500));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(9999, 9999));
        setMinimumSize(new java.awt.Dimension(175, 220));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(175, 220));
        setSize(new java.awt.Dimension(175, 220));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel1.setLayout(new java.awt.BorderLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(imat.IMatApp.class).getContext().getResourceMap(ShoppingListPanel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2, java.awt.BorderLayout.WEST);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(6, 3));
        jScrollPane1.setViewportView(jPanel2);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(20, 24));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, java.awt.BorderLayout.EAST);

        add(jPanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    List<ShoppingItem> siList = IMatDataHandler.getInstance().getShoppingCart().getItems();
    List<ShoppingItem> sListTmp  = new ArrayList<ShoppingItem>(sList);
    List<ShoppingItem> sListTmp2  = new ArrayList<ShoppingItem>(sList);
    
    double tmp = 0;
    double amount = 0;
    for(ShoppingItem si : sListTmp){
        tmp = si.getAmount();
        for(ShoppingItem s : siList){
            amount = s.getAmount();
            if(s.getProduct() == si.getProduct()){
                IMatDataHandler.getInstance().getShoppingCart().removeItem(s);
                IMatDataHandler.getInstance().getShoppingCart().addProduct(s.getProduct(), tmp+amount);
                sListTmp2.remove(si);
                break;
            }
        }        
    }
    
    for(ShoppingItem s : sListTmp2){
        amount = s.getAmount();
        IMatDataHandler.getInstance().getShoppingCart().addProduct(s.getProduct(), amount);
    }
}//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}